# Generated by Django 3.2.6 on 2021-08-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_category', models.CharField(max_length=12)),
                ('item_id', models.IntegerField()),
            ],
        ),
    ]
