# Generated by Django 2.1.7 on 2021-08-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=12)),
                ('item_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile_pic',
        ),
    ]
