# Generated by Django 3.2.6 on 2021-08-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210819_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
